SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `meal`;
DROP TABLE IF EXISTS `food`;
DROP TABLE IF EXISTS `reservations`;
DROP TABLE IF EXISTS `purchase`;
DROP TABLE IF EXISTS `has_food`;
DROP TABLE IF EXISTS `has_meal`;
SET FOREIGN_KEY_CHECKS=1;
